version: '3.4'
services:
  api:
    tty: true
    container_name: "stripe-api"
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: prod
    volumes:
      - .:/usr/src/app
    ports:
      - "5678:5678"
      - "8000:8000"
    restart: unless-stopped